### ISSUE TITLE
First command in UG is list, but app is empty at the start.

### ISSUE THREAD

**Issue by tau-bar** [AY2122S1-CS2103T-W13-4/tp#225]
<img width="877" alt="Screenshot 2021-11-05 at 12 35 51 PM" src="https://user-images.githubusercontent.com/61085398/140458795-ecf1b579-9cd0-4a87-8817-827569558e9d.png">

The app starts off with no sample data, but the first command we ask them to try is `friend --list`. I think a bit weird.

**Comment by kevin9foong** [comment]
yeah good call, lets update the ug
