### ISSUE TITLE
DG broken formatting

### ISSUE THREAD

**Issue by MarcusTXK** [AY2122S1-CS2103T-W13-4/tp#254]
![image](https://user-images.githubusercontent.com/50147457/140683118-dacaf59d-9484-4850-9f25-920ef15ddb5c.png)

**Comment by YeluriKetan** [comment]
I think this is only an issue with the GFMD rendering. This is how it appears in the deployed pages.

![image](https://user-images.githubusercontent.com/77260609/140683238-85c07df6-4096-4059-9463-b1d1ca816be9.png)

**Comment by MarcusTXK** [comment]
I agree it renders correctly in deployed pages, but best to render it correctly there as well.
