### ISSUE TITLE
Commands bolded or not?

### ISSUE THREAD

**Issue by tau-bar** [AY2122S1-CS2103T-W13-4/tp#270]
![image](https://user-images.githubusercontent.com/61085398/140723853-a206fa54-8e56-4732-9c39-3674fae9199f.png)

In this section, commands are bolded. 

![image](https://user-images.githubusercontent.com/61085398/140723883-8b607f3f-5acc-4ff5-9758-241aac199cbb.png)

In other sections, commands are not. Should standardise.

**Comment by MarcusTXK** [comment]
Yes I agree, we should un bold those commands.
